name: mc_locale_keys_class_generator
description: A sample command-line application with basic argument parsing.
version: 0.0.3
repository: https://github.com/msk286/locale-keys-generator

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  recase: ^4.1.0
  yaml: ^3.1.2
  path: ^1.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
